# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92d556fe3ffea24aadd43ff29b55536fa2d5bf7894a2a943905da561e1d5ffaf067e3532be3d4dffaca3dc5820aa8027a3c88c1ff2057c094494dd4d3b0280dc
  # omniauth_provider_key: "453300971529250"
  # omniauth_provider_secret: ed062df5871c343fd450414535151939
  aws_access_key_id: AKIAJKCKKQU4CC25GRRQ
  aws_secret_access_key: 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
  aws_bucket_name: jpking-dev
  # twilio_account_sid: ACc509777384e7ab79f2ea7ce60a53cfc8
  # twilio_auth_token: fd661aa9bf9c2db60eaa65ddd37a1e66
  # twilio_phone_number: +17032911729
  # google_map_key: AIzaSyDARAUd1MlxmQg_Zi6_30yd3Hu3u7qYtBU
  # google_analytics_key: UA-71290751-1

test:
  secret_key_base: fd26547510be86339665aafe2aaadf94c7243979654377700357e7f8cf13c7bff0a8f9edf838daba0f5aec09c70e83193b5fdef9cb75c1c0bbd88bf5832592a8

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
  google_map_key: <%= ENV["GOOGLE_MAP_KEY"] %>
  google_analytics_key: <%= ENV["GOOGLE_ANALYTICS_KEY"] %>